
        var IdObjeto = "";
        var BloqueCreado = "";
        var EtiquetaCreada = "";
        var IddeInserssion = "";
        var IddeInserssiondos = "";
        var IddeInserssionAtriSty = "";
        var IddeInserssionAtriStytemp = "";
        var IdObjetoCreadoUnico = -1;
        var tipodeObjeto = "";
        var idAtributoactual = "";
        var IdObjetosupperior = "";
        var porpiedadCSSCreada = "";
        var momentoTo = 0;
        var historial = [];
        var estadoLec = 0;
        var files;
        var fechaInicioD = "";

        //console.log("uno "+WebObjecsArray.length-1);
        var WebBlocksArray = ["<div id='' class='col-xs-12 col-sm-7 col-md-5 col-lg-3 text-center yellow outoff fullo bg-primary U D A'><h4>BODY</h4></div>",
                              "<div id='' class='col-sm-10 col-xs-offset-1 fullo bg-primary D A'><div class='col-xs-12 full text-center'><h4>TITLE</h4></div><div class='col-xs-12 full'><textarea class='form-control input-sm T' style='resize: vertical;' rows='3'></textarea></div><div class='col-xs-12 full' style='padding-top:5px;padding-bottom:5px;'><div class='col-xs-4 text-center'></div><div class='col-xs-4 text-center'><a id='export' href='#' class='btn btn-primary P' data-toggle='popover' tabindex='0' data-trigger='focus' data-html='true' title='HTML code' data-content='<h1>Works!</h1><h6>Kind of</h6>' data-placement='top'><i class='fa fa-info'></i></a></div><div class='col-xs-4 text-center'></div></div></div>",
                              "<div id='' class='col-sm-10 col-xs-offset-1 fullo bg-primary D A'><div class='col-xs-12 full text-center'><h4>PARAGRAPH</h4></div><div class='col-xs-12 full'><textarea class='form-control input-sm T' style='resize: vertical;' rows='3'></textarea></div><div class='col-xs-12 full' style='padding-top:5px;padding-bottom:5px;'><div class='col-xs-4 text-center'></div><div class='col-xs-4 text-center'><a id='export' href='#' class='btn btn-primary P' data-toggle='popover' tabindex='0' data-trigger='focus' data-html='true' title='HTML code' data-content='<h1>Works!</h1><h6>Kind of</h6>' data-placement='top'><i class='fa fa-info'></i></a></div><div class='col-xs-4 text-center'></div></div></div>",
                               "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>BOLD</h4></div>",
                                "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>DIVITION</h4></div>",
                                "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>LINK</h4></div>",
                                "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary D A'><h4>IMAGE</h4></div>",
                                 "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-warning A'><div class='col-xs-12 full text-center'><h4>HREF</h4></div> <div class='input-group'><input type='text' class='form-control T' /></div></div>",
                                 "<div id='' class='col-sm-10 col-xs-offset-1 fullo bg-warning A S' ><div class='col-xs-12 full text-center'><h4>SRC</h4></div><div class='col-xs-12 full'><select class='form-control '>"+"<?php opendire($dir,$NoRealtivoDos); ?> "+"</select></div></div>",
                                 "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-warning A'><div class='col-xs-12 full text-center'><h4>NAME</h4></div> <div class='input-group'><input type='text' class='form-control T' /></div></div>",
                                      "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-info A'><div class='col-xs-12 full text-center'><h4>BGCOLOR</h4></div> <div class='input-group inColor'><input type='text' value='#ffffff' class='form-control colorpicker-element T' maxlength='7' data-format='hex'/><span class='input-group-addon'><i></i></span></div></div>",
                                      "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-info A'><div class='col-xs-12 full text-center'><h4>MARGIN-LEFT</h4> </div><div class='input-group'><input type='text' class='form-control T ON' /><div class='input-group-addon'><div class='dropdown'><a id='dLabel' data-target='#' class='btn btn-default btn-xs dropdown-toggle' href='#' data-toggle='dropdown' aria-haspopup='true' role='button' aria-expanded='false'><span class='caret'></span></a><ul class='dropdown-menu' role='menu' aria-labelledby='dLabel'><li id='01' class='M'><a>px</a></li><li id='02' class='M'><a>%</a></li><li id='03' class='M'><a>vw</a></li><li id='04' class='M'><a>vh</a></li></ul></div></div></div></div>",
                                      "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-info A'><div class='col-xs-12 full text-center'><h4>WIDTH</h4> </div><div class='input-group'><input type='text' class='form-control T ON' /><div class='input-group-addon'><div class='dropdown'><a id='dLabel' data-target='#' class='btn btn-default btn-xs dropdown-toggle' href='#' data-toggle='dropdown' aria-haspopup='true' role='button' aria-expanded='false'><span class='caret'></span></a><ul class='dropdown-menu' role='menu' aria-labelledby='dLabel'><li id='01' class='M'><a>px</a></li><li id='02' class='M'><a>%</a></li><li id='03' class='M'><a>vw</a></li><li id='04' class='M'><a>vh</a></li></ul></div></div></div></div>",
                                       "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-info A'><div class='col-xs-12 full text-center'><h4>HEIGHT</h4> </div><div class='input-group'><input type='text' class='form-control T ON' /><div class='input-group-addon'><div class='dropdown'><a id='dLabel' data-target='#' class='btn btn-default btn-xs dropdown-toggle' href='#' data-toggle='dropdown' aria-haspopup='true' role='button' aria-expanded='false'><span class='caret'></span></a><ul class='dropdown-menu' role='menu' aria-labelledby='dLabel'><li id='01' class='M'><a>px</a></li><li id='02' class='M'><a>%</a></li><li id='03' class='M'><a>vw</a></li><li id='04' class='M'><a>vh</a></li></ul></div></div></div></div>",
                                        "",
                                        "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-info A'><div class='col-xs-12 full text-center'><h4>MARGIN-RIGHT</h4> </div><div class='input-group'><input type='text' class='form-control T ON' /><div class='input-group-addon'><div class='dropdown'><a id='dLabel' data-target='#' class='btn btn-default btn-xs dropdown-toggle' href='#' data-toggle='dropdown' aria-haspopup='true' role='button' aria-expanded='false'><span class='caret'></span></a><ul class='dropdown-menu' role='menu' aria-labelledby='dLabel'><li id='01' class='M'><a>px</a></li><li id='02' class='M'><a>%</a></li><li id='03' class='M'><a>vw</a></li><li id='04' class='M'><a>vh</a></li></ul></div></div></div></div>",
                                        "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-info A'><div class='col-xs-12 full text-center'><h4>COLOR</h4></div> <div class='input-group inColor'><input type='text' value='#ffffff' class='form-control colorpicker-element T' maxlength='7' data-format='hex'/><span class='input-group-addon'><i></i></span></div></div>",
                                        "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-info A'><div class='col-xs-12 full text-center'><h4>FONT-SIZE</h4> </div><div class='input-group'><input type='text' class='form-control T ON' /><div class='input-group-addon'><div class='dropdown'><a id='dLabel' data-target='#' class='btn btn-default btn-xs dropdown-toggle' href='#' data-toggle='dropdown' aria-haspopup='true' role='button' aria-expanded='false'><span class='caret'></span></a><ul class='dropdown-menu' role='menu' aria-labelledby='dLabel'><li id='01' class='M'><a>px</a></li><li id='02' class='M'><a>%</a></li><li id='03' class='M'><a>vw</a></li><li id='04' class='M'><a>vh</a></li></ul></div></div></div></div>",
                              "",
                             "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>TABLE</h4></div>",
                             "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>T ROW</h4></div>",
                             "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>T HEAD</h4></div>",
                                "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>T CELL</h4></div>",
                              "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-info A'><div class='col-xs-12 full text-center'><h4>BORDER</h4> </div><div class='input-group'><input type='text' class='form-control T ON' /><div class='input-group-addon'><div class='dropdown'><a id='dLabel' data-target='#' class='btn btn-default btn-xs dropdown-toggle' href='#' data-toggle='dropdown' aria-haspopup='true' role='button' aria-expanded='false'><span class='caret'></span></a><ul class='dropdown-menu' role='menu' aria-labelledby='dLabel'><li id='01' class='M'><a>px</a></li><li id='02' class='M'><a>%</a></li><li id='03' class='M'><a>vw</a></li><li id='04' class='M'><a>vh</a></li></ul></div></div></div></div>",
                              "<div id='' class='col-sm-10 col-xs-offset-1 fullo bg-warning A S' ><div class='col-xs-12 full text-center'><h4>SRC</h4></div><div class='col-xs-12 full'><select class='form-control '>"+"<?php opendireD($dirD,$NoRealtivo); ?> "+"</select></div></div>",
                              "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>VIDEO</h4></div>",
                              "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>SORCE</h4></div>",
                              "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-warning A'><div class='col-xs-12 full text-center'><h4>TYPE</h4></div> <div class='input-group'><input type='text' class='form-control T' /></div></div>",
                              "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-warning A'><h4>CONTROLS</h4></div>",
                              "<div id='' class='col-sm-10 col-xs-offset-1 fullo bg-primary D A'><div class='col-xs-12 full text-center'><h4>ABBR</h4></div><div class='col-xs-12 full'><textarea class='form-control input-sm T' style='resize: vertical;' rows='3'></textarea></div><div class='col-xs-12 full' style='padding-top:5px;padding-bottom:5px;'>",
                                "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>ADDRESS</h4></div>",
                                "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>ARTICLE</h4></div>",
                                "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>ASIDE</h4></div>",
                                "<div id='' class='col-sm-10 col-xs-offset-1 fullo bg-primary D A'><div class='col-xs-12 full text-center'><h4>BDI</h4></div><div class='col-xs-12 full'><textarea class='form-control input-sm T' style='resize: vertical;' rows='3'></textarea></div><div class='col-xs-12 full' style='padding-top:5px;padding-bottom:5px;'>",
                                  "<div id='' class='col-sm-10 col-xs-offset-1 fullo bg-primary D A'><div class='col-xs-12 full text-center'><h4>BDO</h4></div><div class='col-xs-12 full'><textarea class='form-control input-sm T' style='resize: vertical;' rows='3'></textarea></div><div class='col-xs-12 full' style='padding-top:5px;padding-bottom:5px;'>",
                                    "<div id='' class='col-sm-10 col-xs-offset-1 fullo bg-primary D A'><div class='col-xs-12 full text-center'><h4>BLOCKQUOTE</h4></div><div class='col-xs-12 full'><textarea class='form-control input-sm T' style='resize: vertical;' rows='3'></textarea></div><div class='col-xs-12 full' style='padding-top:5px;padding-bottom:5px;'>",
                                      "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary D A'><h4>BR</h4></div>",
                                      "<div id='' class='col-sm-10 col-xs-offset-1 fullo bg-primary D A'><div class='col-xs-12 full text-center'><h4>BUTTON</h4></div><div class='col-xs-12 full'><textarea class='form-control input-sm T' style='resize: vertical;' rows='3'></textarea></div><div class='col-xs-12 full' style='padding-top:5px;padding-bottom:5px;'>",
                                        "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary D A'><h4>INPUT</h4></div>",
                                        "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary D A'><h4>OPTION</h4></div>",
                                        "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>D LIST</h4></div>",
                                        "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>D ITEM</h4></div>",
                                        "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>FORM</h4></div>",
                                        "<div id='' class='col-sm-10 col-xs-offset-1 fullo bg-primary D A'><div class='col-xs-12 full text-center'><h4>LABEL</h4></div><div class='col-xs-12 full'><textarea class='form-control input-sm T' style='resize: vertical;' rows='3'></textarea></div><div class='col-xs-12 full' style='padding-top:5px;padding-bottom:5px;'>",
                                          "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>UL</h4></div>",
                                          "<div id='' class='col-xs-10 col-xs-offset-1 text-center outoff fullo bg-primary U D A'><h4>LI</h4></div>",
                                          "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-warning A'><div class='col-xs-12 full text-center'><h4>WIDTH</h4></div> <div class='input-group'><input type='text' class='form-control T' /></div></div>",
                                          "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-warning A'><div class='col-xs-12 full text-center'><h4>HEIGHT</h4></div> <div class='input-group'><input type='text' class='form-control T' /></div></div>",
                                          "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-warning A'><div class='col-xs-12 full text-center'><h4>ALT</h4></div> <div class='input-group'><input type='text' class='form-control T' /></div></div>",
                                          "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-warning A'><div class='col-xs-12 full text-center'><h4>TARGET</h4></div> <div class='input-group'><input type='text' class='form-control T' /></div></div>",
                                          "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-warning A'><div class='col-xs-12 full text-center'><h4>TYPE</h4></div> <div class='input-group'><input type='text' class='form-control T' /></div></div>",
                                          "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-warning A'><div class='col-xs-12 full text-center'><h4>CLASS</h4></div> <div class='input-group'><input type='text' class='form-control T' /></div></div>",
                                          "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-warning A'><div class='col-xs-12 full text-center'><h4>SPAN</h4></div> <div class='input-group'><input type='text' class='form-control T' /></div></div>",
                                          "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-warning A'><div class='col-xs-12 full text-center'><h4>DATA</h4></div> <div class='input-group'><input type='text' class='form-control T' /></div></div>",
                                          "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-warning A'><div class='col-xs-12 full text-center'><h4>VALUE</h4></div> <div class='input-group'><input type='text' class='form-control T' /></div></div>",
                                          "<div id='' class='col-xs-10 col-xs-offset-1 fullo bg-warning A'><div class='col-xs-12 full text-center'><h4>MAX</h4></div> <div class='input-group'><input type='text' class='form-control T' /></div></div>"];

          var WebObjecsArray = ["div$0","h1$1","p$1","b$2","div$2","a$2","img$1","href$3","src$3","name$3","background-color$4","margin-left$4","width$4","height$4","del$5","margin-right$4","color$4","font-size$4","delete$5","table$2","tr$2","th$2","td$2","border$4","src$3","video$2","source$2","type$3","controls$3","abbr$1","address$2","article$2","aside$2","bdi$1","bdo$1","blockquote$1","br$1","button$1","input$1","option$1","dl$2","dt$2","form$2","label$1","ul$2","il$2","width$3","height$3","alt$3","target$3","type$3","class$3","span$3","data$3","value$3","max$3"];
        //console.log("dos "+WebBlocksArray.length-1);
        var FinalString = "";
